name: Build MonoGame Project

on:
  push:
    branches: [main]

jobs:
  build_artifact:
    runs-on: windows-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build project
      run: dotnet build --configuration Release Game/StellarLiberation.csproj

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: StellarLiberationArtifact
        path: ./Game/bin/Release/net6.0/

  create_release:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: StellarLiberationArtifact

      - name: List files
        run: ls -l